apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
  name: pages
  namespace: gamma 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pages
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
    spec:
     containers:
     - image: imsudip84/pages:config
       name: pages
       ports:
       - containerPort: 8080
       env:
        - name: PAGE_CONTENT
          valueFrom:
            configMapKeyRef:
              name: pages-config-map
              key: PAGE_CONTENT

